services:
    run:
        build: .
        container_name: devcontainer
        entrypoint:
            - /bin/bash
        tty: true
        working_dir: /root/app/
        volumes:
          - ../:/root/app
        ports:
          - "3000:3000"