services:
    run:
        build: .
        container_name: devcontainer
        network_mode: host
        entrypoint:
            - /bin/bash
        tty: true
        working_dir: /root/app/
        volumes:
          - ../:/root/app