services:
    run:
        image: ${CONTAINERNAME}
        build: 
            context: .
            args:
              UID: ${UID}
              USERNAME: ${USERNAME} 
              GID: ${GID}
              GROUPNAME: ${GROUPNAME}
              WORKDIR: ${WORKDIR}
        container_name: ${CONTAINERNAME}
        entrypoint:
            - /bin/bash
        tty: true
        volumes:
          - ../:/home/${USERNAME}/${WORKDIR}
        ports:
          - "3000:3000"
        user: "${UID}:${GID}"